import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Card from "../../components/common/Card";
import Button from "../../components/common/Button";
import EmptyState from "../../components/ui/EmptyState";
import LoadingSkeleton from "../../components/ui/LoadingSkeleton";
import {
  getNotifications,
  markNotificationRead,
  deleteNotification,
} from "../../services/notificationService";
import styles from "./Notifications.module.css";

const Notifications = () => {
  const navigate = useNavigate();
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });

  const loadNotifications = async () => {
    setLoading(true);
    setMessage({ type: "", text: "" });

    try {
      const response = await getNotifications();
      setNotifications(response);
    } catch (error) {
      console.error(error);
      setMessage({
        type: "error",
        text: error.response?.data?.detail || "Unable to load notifications.",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, []);

  const handleMarkRead = async (notificationId) => {
    setActionLoading(true);
    setMessage({ type: "", text: "" });

    try {
      const updated = await markNotificationRead(notificationId);
      setNotifications((prev) =>
        prev.map((item) => (item.id === updated.id ? updated : item))
      );
      setMessage({ type: "success", text: "Notification marked as read." });
    } catch (error) {
      console.error(error);
      setMessage({
        type: "error",
        text: error.response?.data?.detail || "Unable to mark notification as read.",
      });
    } finally {
      setActionLoading(false);
    }
  };

  const handleDelete = async (notificationId) => {
    const confirmed = window.confirm("Delete this notification?");
    if (!confirmed) return;

    setActionLoading(true);
    setMessage({ type: "", text: "" });

    try {
      await deleteNotification(notificationId);
      setNotifications((prev) => prev.filter((item) => item.id !== notificationId));
      setMessage({ type: "success", text: "Notification deleted." });
    } catch (error) {
      console.error(error);
      setMessage({
        type: "error",
        text: error.response?.data?.detail || "Unable to delete notification.",
      });
    } finally {
      setActionLoading(false);
    }
  };

  return (
    <div className={styles.notificationsPage}>
      <div className={styles.pageHeader}>
        <div>
          <h2 className={styles.pageTitle}>Notifications</h2>
          <p className={styles.pageSubtitle}>
            View all reminder notifications created by the backend and mark them read.
          </p>
        </div>
      </div>

      <Card className={styles.notificationSummary}>
        <div className={styles.summaryRow}>
          <div>
            <div className={styles.summaryLabel}>Unread</div>
            <div className={styles.summaryValue}>
              {notifications.filter((item) => !item.is_read).length}
            </div>
          </div>
          <div>
            <div className={styles.summaryLabel}>Total</div>
            <div className={styles.summaryValue}>{notifications.length}</div>
          </div>
          <Button variant="outline" onClick={loadNotifications} disabled={loading}>
            Refresh
          </Button>
        </div>
      </Card>

      <Card className={styles.listCard}>
        <div className={styles.cardHeader}>
          <h3>Notification Feed</h3>
        </div>

        {message.text && (
          <div className={`${styles.alert} ${message.type === "success" ? styles.alertSuccess : styles.alertError}`}>
            {message.text}
          </div>
        )}

        {loading ? (
          <LoadingSkeleton lines={6} />
        ) : notifications.length === 0 ? (
          <EmptyState
            title="No notifications yet"
            message="Notifications are generated by due reminders. Enable reminders and open this page to see them here."
            action={
              <Button variant="secondary" onClick={() => navigate("/reminders")}>Browse Reminders</Button>
            }
          />
        ) : (
          <div className={styles.notificationList}>
            {notifications.map((notification) => (
              <div
                key={notification.id}
                className={`${styles.notificationItem} ${notification.is_read ? styles.read : ""}`}
              >
                <div className={styles.notificationHeader}>
                  <div>
                    <div className={styles.notificationTitle}>{notification.title}</div>
                    <div className={styles.notificationType}>{notification.notification_type}</div>
                  </div>
                  <div className={styles.notificationMeta}>
                    <span>{new Date(notification.created_at).toLocaleString()}</span>
                    <span>{notification.is_sent ? "Sent" : "Pending"}</span>
                  </div>
                </div>

                <div className={styles.notificationMessage}>{notification.message}</div>

                <div className={styles.itemActions}>
                  {!notification.is_read && (
                    <Button
                      variant="outline"
                      onClick={() => handleMarkRead(notification.id)}
                      disabled={actionLoading}
                    >
                      Mark as read
                    </Button>
                  )}
                  <Button
                    variant="secondary"
                    onClick={() => handleDelete(notification.id)}
                    disabled={actionLoading}
                  >
                    Delete
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
};

export default Notifications;
